In [8]:
import KNN
import numpy as np
import matplotlib.pyplot as plt

In [4]:
group , labels = KNN.create_dataset()

In [38]:
labels

array(['A', 'A', 'B', 'B'], dtype='<U1')

In [42]:
import operator
def classify0(in_x,dataset,labels,k):
    sq_distance = np.sum(np.power((dataset - in_x),2),axis = 1)
    sorted_dist_indexs = sq_distance.argsort()
    class_count ={}
    for i in range(k):
        vote_label = labels[sorted_dist_indexs[i]]
        class_count[vote_label] = class_count.get(vote_label,0)+1
    sorted_class_count = sorted(class_count.items(),
                               key=operator.itemgetter(1),
                               reverse=True)
    return sorted_class_count[0][0]

In [16]:
a = np.arange(12).reshape(3,4)

In [43]:
classify0([0,0],group,labels,3)

'B'

In [17]:
b = np.arange(4)

In [48]:
a = np.arange(6).reshape(2,3)


In [50]:
np.tile(a,(2,)).shape

(2, 6)

In [23]:
a = np.power(np.sum(np.power((b-a),2),axis = 1),0.5)

array([ 0.,  8., 16.])

In [47]:
np.tile(b,2)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [32]:
random_3_4 = np.random.rand(3,4)

In [35]:
np.argsort(random_3_4,1)

array([[1, 0, 2, 3],
       [3, 1, 0, 2],
       [2, 1, 3, 0]])

In [34]:
random_3_4

array([[0.25764601, 0.19405135, 0.48067439, 0.74484419],
       [0.53602585, 0.42523354, 0.71247696, 0.23121729],
       [0.97788053, 0.50250373, 0.32362318, 0.9724572 ]])